"""Build the mod's sprites/hud.txt from Half-Life's and a file of additions.

The engine takes the FIRST hud.txt it finds on the search path, so a mod that adds one HUD icon
has to ship the whole file: every valve entry, all four resolution blocks, plus its own lines,
with the entry count on the first line kept correct.

    python utils/sprtool/make_hud_txt.py VALVE_HUD.txt ADDITIONS.txt OUT.txt

ADDITIONS.txt holds hud.txt-format lines (name res file x y w h); comments and blanks are ignored.
Every name added must appear at all four resolutions -- the client does not check for a missing one.
"""

import sys
from collections import Counter

RESOLUTIONS = (320, 640, 1280, 2560)


def entry_lines(path):
    with open(path) as f:
        return [l.rstrip("\n") for l in f]


def is_entry(line):
    return len(line.split("//")[0].split()) == 7


def main():
    valve_path, add_path, out_path = sys.argv[1:4]
    valve = entry_lines(valve_path)
    additions = [l for l in entry_lines(add_path) if is_entry(l)]

    seen = Counter()
    for l in additions:
        name, res = l.split()[:2]
        seen[(name, int(res))] += 1
    names = {n for n, _ in seen}
    for n in sorted(names):
        missing = [r for r in RESOLUTIONS if (n, r) not in seen]
        if missing:
            sys.exit(f"{n}: no entry for resolution(s) {missing}")

    body = valve[1:]  # drop valve's count line
    total = sum(1 for l in body if is_entry(l)) + len(additions)
    with open(out_path, "w", newline="\n") as f:
        f.write(f"{total}\n")
        f.write("\n".join(body).rstrip("\n") + "\n")
        f.write("\n// ---- topmod additions (generated by utils/sprtool/make_hud_txt.py) ----\n")
        f.write("\n".join(additions) + "\n")
    print(f"{out_path}: {total} entries ({len(additions)} added)")


if __name__ == "__main__":
    main()
